### ISSUE TITLE
Problem with the duplicated channel

### ISSUE THREAD

**Issue by ZeterickS** [drhacko/Toilet-Bot#3]
Hello ty for your script.

When I move a member in the new created channel from the bot nothing happend can u helpe me?

**Comment by drhacko** [comment]
Did you enter the channel's ID in the script?

**Comment by drhacko** [comment]
Try out [the new index.js](https://github.com/w0298i/Toilet-Bot/blob/01e773d64ef4c1632e3f17ae4bcf929271ab77dd/index.js)
